### ISSUE TITLE
Is the expire job redundant?

### ISSUE THREAD

**Issue by coaxial** [dangmai/docker-tarsnapper#3]
According to https://github.com/miracle2k/tarsnapper/issues/45, `make` implies `expire`. This project seems to assume that both commands need to be run, which seems incorrect.

I'm not sure what the best way would be to fix it. I thought about removing any references to `EXPIRE_COMMAND` altogether, but that would break compatibility.

Or maybe I'm totally missing the point... Why would a user want to run `make` and `expire` both if `make` also expires? Is there a use case I didn't think about?

**Comment by dangmai** [comment]
You're right! Unfortunately I can't really remember why it was like that in the first place (there's a very high likelihood that I was under the impression `expire` needs to be run separately, which is clearly wrong - or maybe it was old behavior).

I'm okay with removing `EXPIRE_COMMAND` altogether - for normal usage of this Docker image I don't foresee it causing a huge amount of problem. Perhaps we can detect if the environmental variable `EXPIRE_COMMAND` exists in the container, and if it does, throw a warning or something.

**Comment by dangmai** [comment]
An alternative would be to run the `make` command with `--no-expire` if backwards compatibility is deemed to be very important.
